kafka-config:
  bootstrap-servers: localhost:19892, Localhost:29692, Localhost:39692
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://Localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 168
  linger-ms: 5
  request-timeout-ms: 66600
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  payment-consumer-group-id: payment-topic-consumer
  restaurant-approval-consumer-group-id: restaurant-approval-topic-consumer
  customer-group-id: customer-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 16600
  heartbeat-interval-ms: 3066
  max-poll-interval-ms: 360060
  max-poll-records: 568
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1